def display_board(board_dict):
    print("           |           |")
    print("           |           |")
    print(f"     {board_dict[1]}      |     {board_dict[2]}     |     {board_dict[3]}")
    print("           |           |")
    print("           |           |")
    print("-----------+-----------+-----------")
    print("           |           |")
    print("           |           |")
    print(f"     {board_dict[4]}      |     {board_dict[5]}     |     {board_dict[6]}")
    print("           |           |")
    print("           |           |")
    print("-----------+-----------+-----------")
    print("           |           |")
    print("           |           |")
    print(f"     {board_dict[7]}      |     {board_dict[8]}     |     {board_dict[9]}")
    print("           |           |")
    print("           |           |")